### ISSUE TITLE
Trouble Running `npm run start`

### ISSUE THREAD

**Issue by AryanJ-NYC** [springload/draftail#283]
### Describe the bug

I followed the contributing instructions [here](https://github.com/springload/draftail/blob/master/docs/CONTRIBUTING.md).

At `npm run start`, I get the following error:
```
ERROR in multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
Module not found: Error: Can't resolve 'babel-loader' in '/Users/aryan/Documents/practice/draftail'
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true main[2]
```

### Which terms did you search for in the documentation and issue tracker?
storybook
babel-loader

### Environment

macOS Mojave Version 10.14.6
Node 12.14.0

### Steps to reproduce

1. First, clone a brand new `draftail` repository.
2. Then, follow the contributing instructions [here](https://github.com/springload/draftail/blob/master/docs/CONTRIBUTING.md)
3. Finally, see red letters (aka an error)

### Expected behavior
The storybook server starts.

### Actual behavior
A wild error appeared!

![Screen Shot 2019-12-25 at 11 11 43 PM](https://user-images.githubusercontent.com/8263430/71457540-5ab53e00-276c-11ea-854f-83081b5959ce.png)

**Comment by thibaudcolas** [comment]
Hey @AryanJ-NYC, thank you for reporting this.

I followed those exact steps as well with a clean install, and it worked as expected. Here are the steps I took and output – do you see anything that’s different in your case?

```
$ git clone git@github.com:springload/draftail.git
Cloning into 'draftail'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 7664 (delta 7), reused 4 (delta 2), pack-reused 7652
Receiving objects: 100% (7664/7664), 4.79 MiB | 6.62 MiB/s, done.
Resolving deltas: 100% (5599/5599), done.
> :Dev/playground
$ cd draftail
CHANGELOG.md        dangerfile.js       flow-typed          package-lock.json   public              tests
LICENSE             docs                jest.config.js      package.json        rollup.config.js
README.md           examples            lib                 prettier.config.js  stylelint.config.js
> :playground/draftail on  master via ⬢ v12.2.0
$ nvm install
Found '~/Dev/playground/draftail/.nvmrc' with version <12>
Downloading and installing node v12.14.0...
Downloading https://nodejs.org/dist/v12.14.0/node-v12.14.0-darwin-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v12.14.0 (npm v6.13.4)
> :playground/draftail on  master via ⬢ v12.14.0
$ npm install

> fsevents@1.2.9 install ~/Dev/playground/draftail/node_modules/@jest/transform/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "~/Dev/playground/draftail/node_modules/@jest/transform/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> fsevents@1.2.4 install ~/Dev/playground/draftail/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.14.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
Traceback (most recent call last):
  File "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 802, in Write
    self.WriteCopies(spec['copies'], extra_outputs, part_of_all)
  File "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1145, in WriteCopies
    env = self.GetSortedXcodeEnv()
  File "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1885, in GetSortedXcodeEnv
    additional_settings)
  File "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1616, in GetSortedXcodeEnv
    additional_settings)
  File "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "~/.nvm/versions/node/v12.14.0/bin/node" "~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=~/Dev/playground/draftail/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=~/Dev/playground/draftail/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi"
gyp ERR! cwd ~/Dev/playground/draftail/node_modules/fsevents
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '~/.nvm/versions/node/v12.14.0/bin/node ~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=~/Dev/playground/draftail/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=~/Dev/playground/draftail/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (~/Dev/playground/draftail/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "~/.nvm/versions/node/v12.14.0/bin/node" "~/Dev/playground/draftail/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd ~/Dev/playground/draftail/node_modules/fsevents
node-pre-gyp ERR! node -v v12.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute '~/.nvm/versions/node/v12.14.0/bin/node ~/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=~/Dev/playground/draftail/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=~/Dev/playground/draftail/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)

> puppeteer@1.20.0 install ~/Dev/playground/draftail/node_modules/react-benchmark/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 110.2 Mb [====================] 100% 0.0s

> puppeteer@1.11.0 install ~/Dev/playground/draftail/node_modules/puppeteer
> node install.js

Downloading Chromium r609904 - 82.7 Mb [====================] 100% 0.0s
Chromium downloaded to ~/Dev/playground/draftail/node_modules/puppeteer/.local-chromium/mac-609904

> core-js@2.6.10 postinstall ~/Dev/playground/draftail/node_modules/@babel/polyfill/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/addon-storyshots/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/addon-viewport/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/addons/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/api/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/channel-postmessage/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/channels/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/client-api/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/client-logger/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/components/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/core-events/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/core/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/node-logger/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/react/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/router/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/theming/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/@storybook/ui/node_modules/core-js
> node postinstall || echo "ignore"


> axe-core@3.1.2 postinstall ~/Dev/playground/draftail/node_modules/axe-core
> node build/utils/postinstall.js


> core-js-pure@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/core-js-pure
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/lazy-universal-dotenv/node_modules/core-js
> node postinstall || echo "ignore"


> core-js@3.4.0 postinstall ~/Dev/playground/draftail/node_modules/simplebar/node_modules/core-js
> node postinstall || echo "ignore"


> draftail@1.3.0 prepare ~/Dev/playground/draftail
> ./.githooks/deploy.sh

Git hooks deployed to .git/hooks. The hooks automatically check your code on every commit.
To bypass them for a single commit, use: git commit --no-verify
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 3314 packages from 1448 contributors and audited 124481 packages in 113.547s

4 packages are looking for funding
  run `npm fund` for details

found 1959 vulnerabilities (3 low, 15 moderate, 1939 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
> :playground/draftail on  master via ⬢ v12.14.0
$ touch .env
> :playground/draftail on  master via ⬢ v12.14.0
$ nvm use
Found '~/Dev/playground/draftail/.nvmrc' with version <12>
npm runNow using node v12.14.0 (npm v6.13.4)
> :playground/draftail on  master via ⬢ v12.14.0
$ npm run start

> draftail@1.3.0 start ~/Dev/playground/draftail
> start-storybook -c .storybook -s public -p 9001

info @storybook/react v5.2.6
info
info => Loading static files from: ~/Dev/playground/draftail/public .
info => Loading presets
info => Loading presets
info => Loading custom addons config.
info => Loading custom Webpack config (full-control mode).
info => Using base config because react-scripts is not installed.
12% building 23/36 modules 13 active ~/Dev/playground/draftail/node_modules/ansi-html/index.js
  When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when needed.
  Please remove the direct import of `core-js` or use `useBuiltIns: 'entry'` instead.
webpack built 88dff5beb38919d41f54 in 17867ms
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 5.2.6 started                          │
│   16 s for manager and 19 s for preview            │
│                                                    │
│   Local:            http://localhost:9001/         │
│   On your network:  http://192.168.0.10:9001/      │
│                                                    │
│   A new version (5.2.8) is available!              │
│                                                    │
│   Read full changelog here: https://git.io/fhFYe   │
│                                                    │
╰────────────────────────────────────────────────────╯
```

**Comment by AryanJ-NYC** [comment]
Sorry @thibaudcolas. Went through it again and it worked.

It doesn't work with a `yarn install,` apparently. Apologies for not following the contributors' guide well enough!
